{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red255\green255\blue255;\red0\green0\blue0;\red46\green174\blue187;
}
{\*\expandedcolortbl;;\csgray\c100000;\csgray\c0;\cssrgb\c20196\c73240\c78250;
}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf2 \cb3 \CocoaLigature0   GNU nano 4.8                  filebeat-config.yml                             \cf3 \cb1 \
\cf4   # The number of seconds to wait before trying to reconnect to Elasticsearch\cf3 \
\cf4   # after a network error. After waiting backoff.init seconds, the Beat\cf3 \
\cf4   # tries to reconnect. If the attempt fails, the backoff timer is increased\cf3 \
\cf4   # exponentially up to backoff.max. After a successful connection, the backoff\cf3 \
\cf4   # timer is reset. The default is 1s.\cf3 \
\cf4   #backoff.init: 1s\cf3 \
\
\cf4   # The maximum number of seconds to wait before attempting to connect to\cf3 \
\cf4   # Elasticsearch after a network error. The default is 60s.\cf3 \
\cf4   #backoff.max: 60s\cf3 \
\
\cf4   # Configure HTTP request timeout before failing an request to Elasticsearch.\cf3 \
\cf4   #timeout: 90\cf3 \
\
\cf4   # Use SSL settings for HTTPS.\cf3 \
\cf4   #ssl.enabled: true\cf3 \
\
\cf4   # Configure SSL verification mode. If `none` is configured, all server hosts\cf3 \
\cf4   # and certificates will be accepted. In this mode, SSL based connections are\cf3 \
\cf4   # susceptible to man-in-the-middle attacks. Use only for testing. Default is\cf3 \
\cf4   # `full`.\cf3 \
\cf4   #ssl.verification_mode: full\cf3 \
\
\cf4   # List of supported/valid TLS versions. By default all TLS versions from 1.0 \cf2 \cb3 >\cf3 \cb1 \
\cf4   # 1.2 are enabled.\cf3 \
\cf4   #ssl.supported_protocols: [TLSv1.0, TLSv1.1, TLSv1.2]\cf3 \
\
\cf4   # SSL configuration. The default is off.\cf3 \
\cf4   # List of root certificates for HTTPS server verifications\cf3 \
\cf4   #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]\cf3 \
\
\cf4   # Certificate for SSL client authentication\cf3 \
\cf4   #ssl.certificate: "/etc/pki/client/cert.pem"\cf3 \
\
\cf4   # Client certificate key\cf3 \
\cf4   #ssl.key: "/etc/pki/client/cert.key"\cf3 \
\
\cf4   # Optional passphrase for decrypting the certificate key.\cf3 \
\cf4   #ssl.key_passphrase: ''\cf3 \
\
\cf4   # Configure cipher suites to be used for SSL connections\cf3 \
\cf4   #ssl.cipher_suites: []\cf3 \
\
\cf4   # Configure curve types for ECDHE-based cipher suites\cf3 \
\cf4   #ssl.curve_types: []\cf3 \
\
\cf4   # Configure what types of renegotiation are supported. Valid options are\cf3 \
\cf4   # never, once, and freely. Default is never.\cf3 \
\cf4   #ssl.renegotiation: never\cf3 \
\
\cf4   #metrics.period: 10s\cf3 \
\cf4   #state.period: 1m\cf3 \
\
\cf4 #================================ HTTP Endpoint ===============================\cf2 \cb3 >\cf3 \cb1 \
\cf4 # Each beat can expose internal metrics through a HTTP endpoint. For security\cf3 \
\cf4 # reasons the endpoint is disabled by default. This feature is currently experi\cf2 \cb3 >\cf3 \cb1 \
\cf4 # Stats can be access through http://localhost:5066/stats . For pretty JSON out\cf2 \cb3 >\cf3 \cb1 \
\cf4 # append ?pretty to the URL.\cf3 \
\
\cf4 # Defines if the HTTP endpoint is enabled.\cf3 \
\cf4 #http.enabled: false\cf3 \
\
\cf4 # The HTTP endpoint will bind to this hostname, IP address, unix socket or name\cf2 \cb3 >\cf3 \cb1 \
\cf4 # When using IP addresses, it is recommended to only use localhost.\cf3 \
\cf4 #http.host: localhost\cf3 \
\
\cf4 # Port on which the HTTP endpoint will bind. Default is 5066.\cf3 \
\cf4 #http.port: 5066\cf3 \
\
\cf4 # Define which user should be owning the named pipe.\cf3 \
\cf4 #http.named_pipe.user:\cf3 \
\
\cf4 # Define which the permissions that should be applied to the named pipe, use th\cf2 \cb3 >\cf3 \cb1 \
\cf4 # Descriptor Definition Language (SDDL) to define the permission. This option c\cf2 \cb3 >\cf3 \cb1 \
\cf4 # `http.user`.\cf3 \
\cf4 #http.named_pipe.security_descriptor:\cf3 \
\
\cf4 #============================= Process Security ================================\cf3 \
\
\cf4 # Enable or disable seccomp system call filtering on Linux. Default is enabled.\cf3 \
\cf4 #seccomp.enabled: true\cf3 \
\
\cf4 #================================= Migration ==================================\cf3 \
\
\cf4 # This allows to enable 6.7 migration aliases\cf3 \
\cf4 #migration.6_to_7.enabled: false}