{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\csgray\c100000;\csgray\c0;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf2 \cb3 \CocoaLigature0   GNU nano 4.8                    install-elk.yml                               \cf3 \cb1 \
---\
  - name: Elk Playbook\
    hosts: elk\
    become: true\
    tasks:\
\
         - name: set vm.max_map_count to 262144 in sysctl\
           sysctl:\
             name: vm.max_map_count\
             value: 262144\
             reload: yes\
\
\
         - name: Install docker.io\
           apt:\
             update_cache: yes\
             name: docker.io\
             state: present\
\
         - name: Install python3-pip\
           apt:\
             name: python3-pip\
             state: present\
\
         - name: Install Pip Package\
           pip:\
             name: docker\
             state: present\
\
         - name: Install Container\
           docker_container:\
              name: elk\
              image: sebp/elk:761\
              state: started\
              restart_policy: always\
              published_ports: 5601:5601,9200:9200,5044:5044\
\
         - name: Start Docker on VM Restart\
           systemd:\
              name: docker\
              enabled: yes}