{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\csgray\c100000;\csgray\c0;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf2 \cb3 \CocoaLigature0   GNU nano 4.8                metricbeat-playbook.yml                           \cf3 \cb1 \
---\
- hosts: elk\
  become: yes\
  tasks:\
\
   - name: Download Metricbeat deb\
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbea\cf2 \cb3 >\cf3 \cb1 \
\
   - name: Install Meticbeat deb\
     command: dpkg -i metricbeat-7.4.0-amd64.deb\
\
   - name: Drop In metricbeat.yml\
     copy:\
       src: /etc/ansible/metricbeat-config.yml\
       dest: /etc/metricbeat.yml\
\
   - name: Enable and config system module\
     command: sudo metricbeat modules enable docker\
\
   - name: Setup Metricbeat\
     command: metricbeat setup -e\
\
   - name: Start Metricbeat service\
     command: sudo service metricbeat start\
\
   - name: Start Metricbeat on VM Restart\
     systemd:\
       name: metricbeat\
       enabled: yes\
}